
package eaa.chapter15.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://service.server.chapter15.eaa/")
public interface PersonService {


    /**
     * 
     * @param arg0
     * @return
     *     returns eaa.chapter15.client.PersonDTO
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPerson", targetNamespace = "http://service.server.chapter15.eaa/", className = "eaa.chapter15.client.FindPerson")
    @ResponseWrapper(localName = "findPersonResponse", targetNamespace = "http://service.server.chapter15.eaa/", className = "eaa.chapter15.client.FindPersonResponse")
    public PersonDTO findPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0)
        throws ApplicationException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://service.server.chapter15.eaa/", className = "eaa.chapter15.client.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://service.server.chapter15.eaa/", className = "eaa.chapter15.client.CreatePersonResponse")
    public long createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1)
        throws ApplicationException_Exception
    ;

}
