
package eaa.chapter15.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PersonServiceService", targetNamespace = "http://service.server.chapter15.eaa/", wsdlLocation = "http://localhost:8080/eaa/person-ws?wsdl")
public class PersonServiceService
    extends Service
{

    private final static URL PERSONSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/eaa/person-ws?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PERSONSERVICESERVICE_WSDL_LOCATION = url;
    }

    public PersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceService() {
        super(PERSONSERVICESERVICE_WSDL_LOCATION, new QName("http://service.server.chapter15.eaa/", "PersonServiceService"));
    }

    /**
     * 
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonService getPersonServicePort() {
        return (PersonService)super.getPort(new QName("http://service.server.chapter15.eaa/", "PersonServicePort"), PersonService.class);
    }

}
